// Small, verified reference tables for categories with no free public API.
// Only well-documented facts are listed; any year not present renders as "Data unavailable".

/** Highest-grossing film released worldwide in each year (box office). */
export const TOP_FILM: Record<number, string> = {
  1990: "Ghost",
  1991: "Terminator 2: Judgment Day",
  1992: "Aladdin",
  1993: "Jurassic Park",
  1994: "The Lion King",
  1995: "Die Hard with a Vengeance",
  1996: "Independence Day",
  1997: "Titanic",
  1998: "Armageddon",
  1999: "Star Wars: Episode I – The Phantom Menace",
  2000: "Mission: Impossible 2",
  2001: "Harry Potter and the Philosopher's Stone",
  2002: "The Lord of the Rings: The Two Towers",
  2003: "The Lord of the Rings: The Return of the King",
  2004: "Shrek 2",
  2005: "Harry Potter and the Goblet of Fire",
  2006: "Pirates of the Caribbean: Dead Man's Chest",
  2007: "Pirates of the Caribbean: At World's End",
  2008: "The Dark Knight",
  2009: "Avatar",
  2010: "Toy Story 3",
  2011: "Harry Potter and the Deathly Hallows – Part 2",
  2012: "The Avengers",
  2013: "Frozen",
  2014: "Transformers: Age of Extinction",
  2015: "Star Wars: The Force Awakens",
  2016: "Captain America: Civil War",
  2017: "Star Wars: The Last Jedi",
  2018: "Avengers: Infinity War",
  2019: "Avengers: Endgame",
  2020: "The Eight Hundred",
  2021: "Spider-Man: No Way Home",
  2022: "Avatar: The Way of Water",
  2023: "Barbie",
};

/** Billboard Year-End Hot 100 number-one single. */
export const TOP_SONG: Record<number, [string, string]> = {
  1990: ["Hold On", "Wilson Phillips"],
  1991: ["(Everything I Do) I Do It for You", "Bryan Adams"],
  1992: ["End of the Road", "Boyz II Men"],
  1993: ["I Will Always Love You", "Whitney Houston"],
  1994: ["The Sign", "Ace of Base"],
  1995: ["Gangsta's Paradise", "Coolio feat. L.V."],
  1996: ["Macarena (Bayside Boys Mix)", "Los del Río"],
  1997: ["Candle in the Wind 1997", "Elton John"],
  1998: ["Too Close", "Next"],
  1999: ["Believe", "Cher"],
  2000: ["Breathe", "Faith Hill"],
  2001: ["Hanging by a Moment", "Lifehouse"],
  2002: ["How You Remind Me", "Nickelback"],
  2003: ["In da Club", "50 Cent"],
  2004: ["Yeah!", "Usher feat. Lil Jon & Ludacris"],
  2005: ["We Belong Together", "Mariah Carey"],
  2006: ["Bad Day", "Daniel Powter"],
  2007: ["Irreplaceable", "Beyoncé"],
  2008: ["Low", "Flo Rida feat. T-Pain"],
  2009: ["Boom Boom Pow", "The Black Eyed Peas"],
  2010: ["Tik Tok", "Kesha"],
  2011: ["Rolling in the Deep", "Adele"],
  2012: ["Somebody That I Used to Know", "Gotye feat. Kimbra"],
  2013: ["Thrift Shop", "Macklemore & Ryan Lewis"],
  2014: ["Happy", "Pharrell Williams"],
  2015: ["Uptown Funk", "Mark Ronson feat. Bruno Mars"],
  2016: ["Love Yourself", "Justin Bieber"],
  2017: ["Shape of You", "Ed Sheeran"],
  2018: ["God's Plan", "Drake"],
  2019: ["Old Town Road", "Lil Nas X"],
  2020: ["Blinding Lights", "The Weeknd"],
  2021: ["Levitating", "Dua Lipa"],
  2022: ["Heat Waves", "Glass Animals"],
  2023: ["Last Night", "Morgan Wallen"],
};

/** Landmark consumer technology launched that year. */
export const TECH: Record<number, [string, string]> = {
  1991: ["World Wide Web", "The first website went public, opening the web to everyone."],
  1995: ["Windows 95", "Brought the Start menu and taskbar to millions of PCs."],
  1998: ["Google", "Google Inc. was founded and launched its search engine."],
  2001: ["iPod & Wikipedia", "Apple launched the iPod; Wikipedia went online."],
  2003: ["Skype", "Free internet voice calls launched worldwide."],
  2004: ["Facebook", "The social network launched from a college dorm."],
  2005: ["YouTube", "The video-sharing site went live."],
  2006: ["Twitter", "Short status updates were born."],
  2007: ["iPhone", "Apple's multi-touch smartphone was released."],
  2008: ["Android", "The first Android phone (HTC Dream) went on sale."],
  2009: ["Bitcoin", "The first Bitcoin block was mined."],
  2010: ["iPad & Instagram", "Apple's tablet and the photo-sharing app launched."],
  2015: ["Apple Watch", "Apple's smartwatch was released."],
  2022: ["ChatGPT", "OpenAI released its conversational AI to the public."],
};

/** Iconic phone released that year. */
export const PHONE: Record<number, [string, string]> = {
  1996: ["Motorola StarTAC", "One of the first clamshell mobile phones."],
  2000: ["Nokia 3310", "Famous for its durability and the game Snake."],
  2003: ["Nokia 1100", "One of the best-selling phones of all time."],
  2004: ["Motorola RAZR V3", "An ultra-thin flip phone icon."],
  2007: ["iPhone", "Apple's first smartphone."],
  2008: ["HTC Dream", "The first Android phone."],
};

export const F1: Record<number, string> = {
  1990: "Ayrton Senna",
  1991: "Ayrton Senna",
  1992: "Nigel Mansell",
  1993: "Alain Prost",
  1994: "Michael Schumacher",
  1995: "Michael Schumacher",
  1996: "Damon Hill",
  1997: "Jacques Villeneuve",
  1998: "Mika Häkkinen",
  1999: "Mika Häkkinen",
  2000: "Michael Schumacher",
  2001: "Michael Schumacher",
  2002: "Michael Schumacher",
  2003: "Michael Schumacher",
  2004: "Michael Schumacher",
  2005: "Fernando Alonso",
  2006: "Fernando Alonso",
  2007: "Kimi Räikkönen",
  2008: "Lewis Hamilton",
  2009: "Jenson Button",
  2010: "Sebastian Vettel",
  2011: "Sebastian Vettel",
  2012: "Sebastian Vettel",
  2013: "Sebastian Vettel",
  2014: "Lewis Hamilton",
  2015: "Lewis Hamilton",
  2016: "Nico Rosberg",
  2017: "Lewis Hamilton",
  2018: "Lewis Hamilton",
  2019: "Lewis Hamilton",
  2020: "Lewis Hamilton",
  2021: "Max Verstappen",
  2022: "Max Verstappen",
  2023: "Max Verstappen",
};

export const WIMBLEDON: Record<number, string> = {
  1990: "Stefan Edberg",
  1991: "Michael Stich",
  1992: "Andre Agassi",
  1993: "Pete Sampras",
  1994: "Pete Sampras",
  1995: "Pete Sampras",
  1996: "Richard Krajicek",
  1997: "Pete Sampras",
  1998: "Pete Sampras",
  1999: "Pete Sampras",
  2000: "Pete Sampras",
  2001: "Goran Ivanišević",
  2002: "Lleyton Hewitt",
  2003: "Roger Federer",
  2004: "Roger Federer",
  2005: "Roger Federer",
  2006: "Roger Federer",
  2007: "Roger Federer",
  2008: "Rafael Nadal",
  2009: "Roger Federer",
  2010: "Rafael Nadal",
  2011: "Novak Djokovic",
  2012: "Roger Federer",
  2013: "Andy Murray",
  2014: "Novak Djokovic",
  2015: "Novak Djokovic",
  2016: "Andy Murray",
  2017: "Roger Federer",
  2018: "Novak Djokovic",
  2019: "Novak Djokovic",
  2021: "Novak Djokovic",
  2022: "Novak Djokovic",
  2023: "Carlos Alcaraz",
};

export const NBA: Record<number, string> = {
  1990: "Detroit Pistons",
  1991: "Chicago Bulls",
  1992: "Chicago Bulls",
  1993: "Chicago Bulls",
  1994: "Houston Rockets",
  1995: "Houston Rockets",
  1996: "Chicago Bulls",
  1997: "Chicago Bulls",
  1998: "Chicago Bulls",
  1999: "San Antonio Spurs",
  2000: "Los Angeles Lakers",
  2001: "Los Angeles Lakers",
  2002: "Los Angeles Lakers",
  2003: "San Antonio Spurs",
  2004: "Detroit Pistons",
  2005: "San Antonio Spurs",
  2006: "Miami Heat",
  2007: "San Antonio Spurs",
  2008: "Boston Celtics",
  2009: "Los Angeles Lakers",
  2010: "Los Angeles Lakers",
  2011: "Dallas Mavericks",
  2012: "Miami Heat",
  2013: "Miami Heat",
  2014: "San Antonio Spurs",
  2015: "Golden State Warriors",
  2016: "Cleveland Cavaliers",
  2017: "Golden State Warriors",
  2018: "Golden State Warriors",
  2019: "Toronto Raptors",
  2020: "Los Angeles Lakers",
  2021: "Milwaukee Bucks",
  2022: "Golden State Warriors",
  2023: "Denver Nuggets",
};

export const FIFA_WC: Record<number, string> = {
  1990: "West Germany",
  1994: "Brazil",
  1998: "France",
  2002: "Brazil",
  2006: "Italy",
  2010: "Spain",
  2014: "Germany",
  2018: "France",
  2022: "Argentina",
};

/** Best-selling passenger car in the United States (annual sales; excludes pickup trucks). [model, Wikipedia article] */
export const CAR_US: Record<number, string> = {
  1990: "Honda Accord",
  1991: "Honda Accord",
  1992: "Ford Taurus",
  1993: "Ford Taurus",
  1994: "Ford Taurus",
  1995: "Ford Taurus",
  1996: "Ford Taurus",
  1997: "Toyota Camry",
  1998: "Toyota Camry",
  1999: "Toyota Camry",
  2000: "Toyota Camry",
  2001: "Honda Accord",
  2002: "Toyota Camry",
  2003: "Toyota Camry",
  2004: "Toyota Camry",
  2005: "Toyota Camry",
  2006: "Toyota Camry",
  2007: "Toyota Camry",
  2008: "Toyota Camry",
  2009: "Toyota Camry",
  2010: "Toyota Camry",
  2011: "Toyota Camry",
  2012: "Toyota Camry",
  2013: "Toyota Camry",
  2014: "Toyota Camry",
  2015: "Toyota Camry",
  2016: "Toyota Camry",
  2017: "Toyota Camry",
  2018: "Toyota Camry",
  2019: "Toyota Camry",
  2020: "Toyota Camry",
  2021: "Toyota Camry",
  2022: "Toyota Camry",
};

/** #1 US primetime series by Nielsen ratings for the TV season starting in that year. [title, Wikipedia article] */
export const TV_NIELSEN: Record<number, [string, string]> = {
  1990: ["Cheers", "Cheers"],
  1991: ["60 Minutes", "60 Minutes"],
  1992: ["60 Minutes", "60 Minutes"],
  1993: ["Home Improvement", "Home Improvement (TV series)"],
  1994: ["Seinfeld", "Seinfeld"],
  1995: ["ER", "ER (TV series)"],
  1996: ["ER", "ER (TV series)"],
  1997: ["Seinfeld", "Seinfeld"],
  1998: ["ER", "ER (TV series)"],
  1999: ["Who Wants to Be a Millionaire", "Who Wants to Be a Millionaire? (American game show)"],
  2000: ["Survivor", "Survivor (American TV series)"],
  2001: ["Friends", "Friends"],
  2002: ["CSI: Crime Scene Investigation", "CSI: Crime Scene Investigation"],
  2003: ["American Idol", "American Idol"],
  2004: ["American Idol", "American Idol"],
  2005: ["American Idol", "American Idol"],
  2006: ["American Idol", "American Idol"],
  2007: ["American Idol", "American Idol"],
  2008: ["American Idol", "American Idol"],
  2009: ["American Idol", "American Idol"],
  2010: ["American Idol", "American Idol"],
  2011: ["Sunday Night Football", "NBC Sunday Night Football"],
  2012: ["Sunday Night Football", "NBC Sunday Night Football"],
  2013: ["Sunday Night Football", "NBC Sunday Night Football"],
  2014: ["Sunday Night Football", "NBC Sunday Night Football"],
  2015: ["Sunday Night Football", "NBC Sunday Night Football"],
  2016: ["Sunday Night Football", "NBC Sunday Night Football"],
  2017: ["Sunday Night Football", "NBC Sunday Night Football"],
  2018: ["Sunday Night Football", "NBC Sunday Night Football"],
  2019: ["Sunday Night Football", "NBC Sunday Night Football"],
  2020: ["Sunday Night Football", "NBC Sunday Night Football"],
};

/** Wikipedia article titles for curated items whose display name is ambiguous. */
export const WIKI_TITLE: Record<string, string> = {
  iPhone: "iPhone (1st generation)",
  "Motorola RAZR V3": "Motorola Razr",
  "iPod & Wikipedia": "iPod",
  "iPad & Instagram": "iPad (1st generation)",
  Android: "Android (operating system)",
  Google: "Google Search",
  "World Wide Web": "World Wide Web",
  Twitter: "Twitter",
};
