/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as RevealRouteImport } from './routes/reveal'
import { Route as DashAboutRouteImport } from './routes/_dash.about'
import { Route as DashAgeRouteImport } from './routes/_dash.age'
import { Route as DashCalendarRouteImport } from './routes/_dash.calendar'
import { Route as DashCardRouteImport } from './routes/_dash.card'
import { Route as DashCompareRouteImport } from './routes/_dash.compare'
import { Route as DashCountdownRouteImport } from './routes/_dash.countdown'
import { Route as DashDailyPlannerRouteImport } from './routes/_dash.daily-planner'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashHabitTrackerRouteImport } from './routes/_dash.habit-tracker'
import { Route as DashRemindersRouteImport } from './routes/_dash.reminders'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashSnapshotRouteImport } from './routes/_dash.snapshot'
import { Route as DashStatisticsRouteImport } from './routes/_dash.statistics'
import { Route as DashTimelineRouteImport } from './routes/_dash.timeline'
import { Route as DashDailyPlannerIndexRouteImport } from './routes/_dash.daily-planner.index'
import { Route as DashDailyPlannerAddRouteImport } from './routes/_dash.daily-planner.add'
import { Route as DashHabitTrackerIndexRouteImport } from './routes/_dash.habit-tracker.index'
import { Route as DashHabitTrackerAddRouteImport } from './routes/_dash.habit-tracker.add'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const RevealRoute = RevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashAboutRoute = DashAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashRoute,
} as any)
const DashAgeRoute = DashAgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => DashRoute,
} as any)
const DashCalendarRoute = DashCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashRoute,
} as any)
const DashCardRoute = DashCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DashRoute,
} as any)
const DashCompareRoute = DashCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashRoute,
} as any)
const DashCountdownRoute = DashCountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => DashRoute,
} as any)
const DashDailyPlannerRoute = DashDailyPlannerRouteImport.update({
  id: '/daily-planner',
  path: '/daily-planner',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashHabitTrackerRoute = DashHabitTrackerRouteImport.update({
  id: '/habit-tracker',
  path: '/habit-tracker',
  getParentRoute: () => DashRoute,
} as any)
const DashRemindersRoute = DashRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashSnapshotRoute = DashSnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => DashRoute,
} as any)
const DashStatisticsRoute = DashStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => DashRoute,
} as any)
const DashTimelineRoute = DashTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashRoute,
} as any)
const DashDailyPlannerIndexRoute = DashDailyPlannerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashDailyPlannerRoute,
} as any)
const DashDailyPlannerAddRoute = DashDailyPlannerAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashDailyPlannerRoute,
} as any)
const DashHabitTrackerIndexRoute = DashHabitTrackerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashHabitTrackerRoute,
} as any)
const DashHabitTrackerAddRoute = DashHabitTrackerAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => DashHabitTrackerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reveal': typeof RevealRoute
  '/about': typeof DashAboutRoute
  '/age': typeof DashAgeRoute
  '/calendar': typeof DashCalendarRoute
  '/card': typeof DashCardRoute
  '/compare': typeof DashCompareRoute
  '/countdown': typeof DashCountdownRoute
  '/daily-planner': typeof DashDailyPlannerRouteWithChildren
  '/dashboard': typeof DashDashboardRoute
  '/habit-tracker': typeof DashHabitTrackerRouteWithChildren
  '/reminders': typeof DashRemindersRoute
  '/settings': typeof DashSettingsRoute
  '/snapshot': typeof DashSnapshotRoute
  '/statistics': typeof DashStatisticsRoute
  '/timeline': typeof DashTimelineRoute
  '/daily-planner/add': typeof DashDailyPlannerAddRoute
  '/habit-tracker/add': typeof DashHabitTrackerAddRoute
  '/daily-planner/': typeof DashDailyPlannerIndexRoute
  '/habit-tracker/': typeof DashHabitTrackerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reveal': typeof RevealRoute
  '/about': typeof DashAboutRoute
  '/age': typeof DashAgeRoute
  '/calendar': typeof DashCalendarRoute
  '/card': typeof DashCardRoute
  '/compare': typeof DashCompareRoute
  '/countdown': typeof DashCountdownRoute
  '/dashboard': typeof DashDashboardRoute
  '/reminders': typeof DashRemindersRoute
  '/settings': typeof DashSettingsRoute
  '/snapshot': typeof DashSnapshotRoute
  '/statistics': typeof DashStatisticsRoute
  '/timeline': typeof DashTimelineRoute
  '/daily-planner/add': typeof DashDailyPlannerAddRoute
  '/habit-tracker/add': typeof DashHabitTrackerAddRoute
  '/daily-planner': typeof DashDailyPlannerIndexRoute
  '/habit-tracker': typeof DashHabitTrackerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/reveal': typeof RevealRoute
  '/_dash/about': typeof DashAboutRoute
  '/_dash/age': typeof DashAgeRoute
  '/_dash/calendar': typeof DashCalendarRoute
  '/_dash/card': typeof DashCardRoute
  '/_dash/compare': typeof DashCompareRoute
  '/_dash/countdown': typeof DashCountdownRoute
  '/_dash/daily-planner': typeof DashDailyPlannerRouteWithChildren
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/habit-tracker': typeof DashHabitTrackerRouteWithChildren
  '/_dash/reminders': typeof DashRemindersRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/snapshot': typeof DashSnapshotRoute
  '/_dash/statistics': typeof DashStatisticsRoute
  '/_dash/timeline': typeof DashTimelineRoute
  '/_dash/daily-planner/add': typeof DashDailyPlannerAddRoute
  '/_dash/habit-tracker/add': typeof DashHabitTrackerAddRoute
  '/_dash/daily-planner/': typeof DashDailyPlannerIndexRoute
  '/_dash/habit-tracker/': typeof DashHabitTrackerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/reveal'
    | '/about'
    | '/age'
    | '/calendar'
    | '/card'
    | '/compare'
    | '/countdown'
    | '/daily-planner'
    | '/dashboard'
    | '/habit-tracker'
    | '/reminders'
    | '/settings'
    | '/snapshot'
    | '/statistics'
    | '/timeline'
    | '/daily-planner/add'
    | '/habit-tracker/add'
    | '/daily-planner/'
    | '/habit-tracker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/reveal'
    | '/about'
    | '/age'
    | '/calendar'
    | '/card'
    | '/compare'
    | '/countdown'
    | '/dashboard'
    | '/reminders'
    | '/settings'
    | '/snapshot'
    | '/statistics'
    | '/timeline'
    | '/daily-planner/add'
    | '/habit-tracker/add'
    | '/daily-planner'
    | '/habit-tracker'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/reveal'
    | '/_dash/about'
    | '/_dash/age'
    | '/_dash/calendar'
    | '/_dash/card'
    | '/_dash/compare'
    | '/_dash/countdown'
    | '/_dash/daily-planner'
    | '/_dash/dashboard'
    | '/_dash/habit-tracker'
    | '/_dash/reminders'
    | '/_dash/settings'
    | '/_dash/snapshot'
    | '/_dash/statistics'
    | '/_dash/timeline'
    | '/_dash/daily-planner/add'
    | '/_dash/habit-tracker/add'
    | '/_dash/daily-planner/'
    | '/_dash/habit-tracker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  RevealRoute: typeof RevealRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveal': {
      id: '/reveal'
      path: '/reveal'
      fullPath: '/reveal'
      preLoaderRoute: typeof RevealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/about': {
      id: '/_dash/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof DashAboutRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/age': {
      id: '/_dash/age'
      path: '/age'
      fullPath: '/age'
      preLoaderRoute: typeof DashAgeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/calendar': {
      id: '/_dash/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof DashCalendarRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/card': {
      id: '/_dash/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof DashCardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/compare': {
      id: '/_dash/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof DashCompareRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/countdown': {
      id: '/_dash/countdown'
      path: '/countdown'
      fullPath: '/countdown'
      preLoaderRoute: typeof DashCountdownRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/daily-planner': {
      id: '/_dash/daily-planner'
      path: '/daily-planner'
      fullPath: '/daily-planner'
      preLoaderRoute: typeof DashDailyPlannerRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/habit-tracker': {
      id: '/_dash/habit-tracker'
      path: '/habit-tracker'
      fullPath: '/habit-tracker'
      preLoaderRoute: typeof DashHabitTrackerRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/reminders': {
      id: '/_dash/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof DashRemindersRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/snapshot': {
      id: '/_dash/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof DashSnapshotRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/statistics': {
      id: '/_dash/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof DashStatisticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/timeline': {
      id: '/_dash/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof DashTimelineRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/daily-planner/': {
      id: '/_dash/daily-planner/'
      path: '/'
      fullPath: '/daily-planner/'
      preLoaderRoute: typeof DashDailyPlannerIndexRouteImport
      parentRoute: typeof DashDailyPlannerRoute
    }
    '/_dash/daily-planner/add': {
      id: '/_dash/daily-planner/add'
      path: '/add'
      fullPath: '/daily-planner/add'
      preLoaderRoute: typeof DashDailyPlannerAddRouteImport
      parentRoute: typeof DashDailyPlannerRoute
    }
    '/_dash/habit-tracker/': {
      id: '/_dash/habit-tracker/'
      path: '/'
      fullPath: '/habit-tracker/'
      preLoaderRoute: typeof DashHabitTrackerIndexRouteImport
      parentRoute: typeof DashHabitTrackerRoute
    }
    '/_dash/habit-tracker/add': {
      id: '/_dash/habit-tracker/add'
      path: '/add'
      fullPath: '/habit-tracker/add'
      preLoaderRoute: typeof DashHabitTrackerAddRouteImport
      parentRoute: typeof DashHabitTrackerRoute
    }
  }
}

interface DashDailyPlannerRouteChildren {
  DashDailyPlannerAddRoute: typeof DashDailyPlannerAddRoute
  DashDailyPlannerIndexRoute: typeof DashDailyPlannerIndexRoute
}

const DashDailyPlannerRouteChildren: DashDailyPlannerRouteChildren = {
  DashDailyPlannerAddRoute: DashDailyPlannerAddRoute,
  DashDailyPlannerIndexRoute: DashDailyPlannerIndexRoute,
}

const DashDailyPlannerRouteWithChildren =
  DashDailyPlannerRoute._addFileChildren(DashDailyPlannerRouteChildren)

interface DashHabitTrackerRouteChildren {
  DashHabitTrackerAddRoute: typeof DashHabitTrackerAddRoute
  DashHabitTrackerIndexRoute: typeof DashHabitTrackerIndexRoute
}

const DashHabitTrackerRouteChildren: DashHabitTrackerRouteChildren = {
  DashHabitTrackerAddRoute: DashHabitTrackerAddRoute,
  DashHabitTrackerIndexRoute: DashHabitTrackerIndexRoute,
}

const DashHabitTrackerRouteWithChildren =
  DashHabitTrackerRoute._addFileChildren(DashHabitTrackerRouteChildren)

interface DashRouteChildren {
  DashAboutRoute: typeof DashAboutRoute
  DashAgeRoute: typeof DashAgeRoute
  DashCalendarRoute: typeof DashCalendarRoute
  DashCardRoute: typeof DashCardRoute
  DashCompareRoute: typeof DashCompareRoute
  DashCountdownRoute: typeof DashCountdownRoute
  DashDailyPlannerRoute: typeof DashDailyPlannerRouteWithChildren
  DashDashboardRoute: typeof DashDashboardRoute
  DashHabitTrackerRoute: typeof DashHabitTrackerRouteWithChildren
  DashRemindersRoute: typeof DashRemindersRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashSnapshotRoute: typeof DashSnapshotRoute
  DashStatisticsRoute: typeof DashStatisticsRoute
  DashTimelineRoute: typeof DashTimelineRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAboutRoute: DashAboutRoute,
  DashAgeRoute: DashAgeRoute,
  DashCalendarRoute: DashCalendarRoute,
  DashCardRoute: DashCardRoute,
  DashCompareRoute: DashCompareRoute,
  DashCountdownRoute: DashCountdownRoute,
  DashDailyPlannerRoute: DashDailyPlannerRouteWithChildren,
  DashDashboardRoute: DashDashboardRoute,
  DashHabitTrackerRoute: DashHabitTrackerRouteWithChildren,
  DashRemindersRoute: DashRemindersRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashSnapshotRoute: DashSnapshotRoute,
  DashStatisticsRoute: DashStatisticsRoute,
  DashTimelineRoute: DashTimelineRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  RevealRoute: RevealRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
